style_edition = "2024"
wrap_comments = true
format_strings = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
reorder_imports = true
group_imports = "StdExternalCrate"
